"""empty message

Revision ID: 091c5c1f608a
Revises: 645e5cc9b7bb
Create Date: 2025-04-23 18:58:10.661495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091c5c1f608a'
down_revision = '645e5cc9b7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
